### ISSUE TITLE
VERY IMPORTANT: Need a setting for the stores URL

### ISSUE THREAD

**Issue by lucasjkr** [lucasjkr/opencommerce#20]
The HTTP_SERVER and HTTPS_SERVER settings don't seem right to me - it should be obvious that the site's URL is the server it's running on.

BUT!!!

The callback URL's in the payment modules are created using the HTTPS_SERVER global.

Since secure is the norm, i think the "https://" should be hard-coded in (since those services shouldn't even respond to a non-https requrest), but we need to insert the store's address into the request.

I think the solution is a new global that gets configured during installation STORE_URL (which is just the URL without protocol i.e. www.store.com, etc)

**Comment by arnisjuraga** [comment]
Wordpress defines the url and saves into db (which is a headake, if you are moving the site), but - the site is always redirected later to the "settings" url - is it HTTP or HTTPS.

**Comment by lucasjkr** [comment]
I want to take things OUT of settings that shouldn't be modifiable by end users (even people with admin rights to the store), and will put them in text/config files.

The reason being, just because a user has the right to add products, review orders, etc, that doesn't mean they should be trusted with the keys to the kingdom. I know that there are permissions, but those are just a mess. So, I'd rather take settings out of the web UI where possible.

An end user will never need to change the store URL in the UI. If the site is moved to a new server, or the URL changes, then a text file will need to be updated.

Just like I disagree with OC's ability for the admin user to try to toggle SSL on or off in the interface, that could be a disastrous issue that shouldn't be so easy to do.

I liked my SQL Debugger in Copona, but think it should have been implemented solely in config file, rather than a DB setting.

I'm also going to replace whatever is in use currently for sending mails with PHPMailer - email server credentials will be removed from settings and into config.php.

Most of those things are set once and never touch again, or should be done by/with the person that knows what they're doing.

**Comment by arnisjuraga** [comment]
Suggesting to use .php extension for config file, so the file could not be viewed directly depending on any other settings in .htaccess or anywhere

**Comment by lucasjkr** [comment]
Yes. Config file is config.php

It also doesn't reside in a public directory.

Just added a required variable at install time, and it writes the URL as a new constant in config PHP called STORE_URL

**Comment by arnisjuraga** [comment]
Everything is fine about `config`, just referring to:
> and will put them in **text**/config files.
